## 데이터 불러오기

In [1]:
import pandas as pd
df=pd.read_csv('data/heart.csv')

In [2]:
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [3]:
df.describe()

,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [4]:
# 누락치 제거
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [5]:
# 누락치 제거
df=df.dropna(axis=0)

## Categorical Data 변환하기

In [6]:
df.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [7]:
# 범주형 데이터 처리 : One-hot encoding
df2=pd.get_dummies(df,columns=['Sex','ChestPain','Thal','AHD'])

In [8]:
df2

,Age,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,...,Sex_1,ChestPain_asymptomatic,ChestPain_nonanginal,ChestPain_nontypical,ChestPain_typical,Thal_fixed,Thal_normal,Thal_reversable,AHD_No,AHD_Yes
0,63,145,233,1,2,150,0,2.3,3,0.0,...,1,0,0,0,1,1,0,0,1,0
1,67,160,286,0,2,108,1,1.5,2,3.0,...,1,1,0,0,0,0,1,0,0,1
2,67,120,229,0,2,129,1,2.6,2,2.0,...,1,1,0,0,0,0,0,1,0,1
3,37,130,250,0,0,187,0,3.5,3,0.0,...,1,0,1,0,0,0,1,0,1,0
4,41,130,204,0,2,172,0,1.4,1,0.0,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,140,241,0,0,123,1,0.2,2,0.0,...,0,1,0,0,0,0,0,1,0,1
298,45,110,264,0,0,132,0,1.2,2,0.0,...,1,0,0,0,1,0,0,1,0,1
299,68,144,193,1,0,141,0,3.4,2,2.0,...,1,1,0,0,0,0,0,1,0,1
300,57,130,131,0,0,115,1,1.2,2,1.0,...,1,1,0,0,0,0,0,1,0,1
301,57,130,236,0,2,174,0,0.0,2,1.0,...,0,0,0,1,0,0,1,0,0,1

In [9]:
df2.columns

Index(['Age', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR', 'ExAng', 'Oldpeak',
       'Slope', 'Ca', 'Sex_0', 'Sex_1', 'ChestPain_asymptomatic',
       'ChestPain_nonanginal', 'ChestPain_nontypical', 'ChestPain_typical',
       'Thal_fixed', 'Thal_normal', 'Thal_reversable', 'AHD_No', 'AHD_Yes'],
      dtype='object')

## 데이터 표준화

표준화를 통해 변수의 범위, scale, unit을 통일

In [10]:
df=pd.read_csv('data/auto.csv')
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,1,27.0
388,4,97.0,52.0,2130.0,24.6,82,2,44.0
389,4,135.0,84.0,2295.0,11.6,82,1,32.0
390,4,120.0,79.0,2625.0,18.6,82,1,28.0
391,4,119.0,82.0,2720.0,19.4,82,1,31.0

In [11]:
# 표준화
df=(df-df.mean())/df.std()

## SKlearn을 이용한 전처리
SKlearn : 파이썬에서 표준화된 머신러닝 라이브러리

In [14]:
df=pd.read_csv('data/auto.csv')
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,1,27.0
388,4,97.0,52.0,2130.0,24.6,82,2,44.0
389,4,135.0,84.0,2295.0,11.6,82,1,32.0
390,4,120.0,79.0,2625.0,18.6,82,1,28.0
391,4,119.0,82.0,2720.0,19.4,82,1,31.0

In [17]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
# 스케일러 객체 생성
# StandardScaler : 평균 0, 표준편차 0으로 스케일링
scaler = StandardScaler()
output = scaler.fit_transform(df) # numpy array 형태로 반환
output

array([[ 1.48394702,  1.07728956,  0.66413273, ..., -1.62531533,
        -0.71664105, -0.69863841],
       [ 1.48394702,  1.48873169,  1.57459447, ..., -1.62531533,
        -0.71664105, -1.08349824],
       [ 1.48394702,  1.1825422 ,  1.18439658, ..., -1.62531533,
        -0.71664105, -0.69863841],
       ...,
       [-0.86401356, -0.56847897, -0.53247413, ...,  1.63640964,
        -0.71664105,  1.09737414],
       [-0.86401356, -0.7120053 , -0.66254009, ...,  1.63640964,
        -0.71664105,  0.5842277 ],
       [-0.86401356, -0.72157372, -0.58450051, ...,  1.63640964,
        -0.71664105,  0.96908753]])

In [18]:
pd.DataFrame(output, columns=df.columns)

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,1.483947,1.077290,0.664133,0.620540,-1.285258,-1.625315,-0.716641,-0.698638
1,1.483947,1.488732,1.574594,0.843334,-1.466724,-1.625315,-0.716641,-1.083498
2,1.483947,1.182542,1.184397,0.540382,-1.648189,-1.625315,-0.716641,-0.698638
3,1.483947,1.048584,1.184397,0.536845,-1.285258,-1.625315,-0.716641,-0.955212
4,1.483947,1.029447,0.924265,0.555706,-1.829655,-1.625315,-0.716641,-0.826925
...,...,...,...,...,...,...,...,...
387,-0.864014,-0.520637,-0.480448,-0.221125,0.021294,1.636410,-0.716641,0.455941
388,-0.864014,-0.932079,-1.364896,-0.999134,3.287676,1.636410,0.526382,2.636813
389,-0.864014,-0.568479,-0.532474,-0.804632,-1.430430,1.636410,-0.716641,1.097374
390,-0.864014,-0.712005,-0.662540,-0.415627,1.110088,1.636410,-0.716641,0.584228
391,-0.864014,-0.721574,-0.584501,-0.303641,1.400433,1.636410,-0.716641,0.969088

## Polynomial Term 추가하기

선형회귀 모형의 한계를 깨기 위한 방법 (비선형적인 관계 표현하기)
- 다차항 넣기
- 변수간의 상호작용

In [49]:
# 독립변수 추리기
df=pd.read_csv('data/classification_data.csv')
x = df[['X1', 'X2']]
x

          X1        X2
0  -2.056844 -0.752741
1   1.760238  1.558517
2  -0.447763 -1.554927
3   1.008459  0.529517
4   0.636547  0.409058
..       ...       ...
95 -0.129932 -0.797169
96  1.426902  1.244639
97 -0.582968  1.630750
98 -0.619720  1.630840
99  1.938929  0.069963

[100 rows x 2 columns]

In [50]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=False)
output = poly.fit_transform(x)

In [51]:
c = poly.get_feature_names(x.columns)
c

/Users/jung_yujin/miniconda3/envs/dssa/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['X1', 'X2', 'X1^2', 'X1 X2', 'X2^2']

In [52]:
pd.DataFrame(output, columns=c)

          X1        X2      X1^2     X1 X2      X2^2
0  -2.056844 -0.752741  4.230608  1.548270  0.566618
1   1.760238  1.558517  3.098437  2.743361  2.428977
2  -0.447763 -1.554927  0.200492  0.696238  2.417797
3   1.008459  0.529517  1.016990  0.533996  0.280388
4   0.636547  0.409058  0.405191  0.260384  0.167328
..       ...       ...       ...       ...       ...
95 -0.129932 -0.797169  0.016882  0.103577  0.635478
96  1.426902  1.244639  2.036050  1.775978  1.549126
97 -0.582968  1.630750  0.339852 -0.950675  2.659346
98 -0.619720  1.630840  0.384052 -1.010664  2.659641
99  1.938929  0.069963  3.759444  0.135652  0.004895

[100 rows x 5 columns]

In [53]:
# 차수 변경
poly = PolynomialFeatures(degree=3, include_bias=False)
new_output = poly.fit_transform(x)
new_output

array([[-2.05684422e+00, -7.52740645e-01,  4.23060816e+00,
         1.54827025e+00,  5.66618479e-01, -8.70170194e+00,
        -3.18455071e+00, -1.16544594e+00, -4.26516759e-01],
       [ 1.76023771e+00,  1.55851748e+00,  3.09843680e+00,
         2.74336124e+00,  2.42897673e+00,  5.45398529e+00,
         4.82896790e+00,  4.27557644e+00,  3.78560269e+00],
       [-4.47762816e-01, -1.55492674e+00,  2.00491540e-01,
         6.96238378e-01,  2.41779718e+00, -8.97726565e-02,
        -3.11749657e-01, -1.08259967e+00, -3.75949749e+00],
       [ 1.00845900e+00,  5.29516997e-01,  1.01698955e+00,
         5.33996181e-01,  2.80388250e-01,  1.02559226e+00,
         5.38513253e-01,  2.82760054e-01,  1.48470344e-01],
       [ 6.36546533e-01,  4.09057947e-01,  4.05191488e-01,
         2.60384418e-01,  1.67328404e-01,  2.57923237e-01,
         1.65746798e-01,  1.06512315e-01,  6.84470133e-02],
       [ 1.31066242e+00, -1.22557959e+00,  1.71783597e+00,
        -1.60632111e+00,  1.50204533e+00,  2.25150305e+00,
        -2.10534470e+00,  1.96867436e+00, -1.84087609e+00],
       [ 9.92554161e-01,  2.15415626e-01,  9.85163762e-01,
         2.13811676e-01,  4.64038919e-02,  9.77828391e-01,
         2.12219668e-01,  4.60583759e-02,  9.99612341e-03],
       [ 1.87466070e+00, -1.56342719e+00,  3.51435273e+00,
        -2.93089550e+00,  2.44430456e+00,  6.58821893e+00,
        -5.49443459e+00,  4.58224170e+00, -3.82149220e+00],
       [-1.66770837e+00, -4.72954307e-01,  2.78125119e+00,
         7.88749854e-01,  2.23685777e-01, -4.63831588e+00,
        -1.31540473e+00, -3.73042641e-01, -1.05793152e-01],
       [ 2.62737261e-02, -8.13062974e-01,  6.90308684e-04,
        -2.13621939e-02,  6.61071399e-01,  1.81369813e-05,
        -5.61264431e-04,  1.73688089e-02, -5.37492678e-01],
       [-1.46446806e+00, -1.81286708e+00,  2.14466669e+00,
         2.65488593e+00,  3.28648704e+00, -3.14079586e+00,
        -3.88799564e+00, -4.81295529e+00, -5.95796416e+00],
       [ 1.35468139e+00,  2.45515781e+00,  1.83516166e+00,
         3.32595658e+00,  6.02779986e+00,  2.48605934e+00,
         4.50561148e+00,  8.16574827e+00,  1.47991999e+01],
       [-1.21510104e+00,  1.28395605e+00,  1.47647053e+00,
        -1.56013633e+00,  1.64854314e+00, -1.79406088e+00,
         1.89572328e+00, -2.00314648e+00,  2.11665694e+00],
       [-6.93216427e-01, -2.45240240e+00,  4.80549015e-01,
         1.70004563e+00,  6.01427751e+00, -3.33124472e-01,
        -1.17849956e+00, -4.16919597e+00, -1.47494286e+01],
       [-9.49745374e-01, -7.86036196e-01,  9.02016276e-01,
         7.46534241e-01,  6.17852902e-01, -8.56685785e-01,
        -7.09017442e-01, -5.86802935e-01, -4.85654745e-01],
       [ 2.08435040e+00, -7.56736424e-01,  4.34451658e+00,
        -1.57730387e+00,  5.72650016e-01,  9.05549487e+00,
        -3.28765394e+00,  1.19360329e+00, -4.33345126e-01],
       [-2.45725965e-01, -7.05941388e-01,  6.03812499e-02,
         1.73468129e-01,  4.98353243e-01, -1.48372409e-02,
        -4.26256234e-02, -1.22458332e-01, -3.51808180e-01],
       [ 1.86549769e+00, -1.33799892e+00,  3.48008163e+00,
        -2.49603389e+00,  1.79024111e+00,  6.49208423e+00,
        -4.65634546e+00,  3.33969066e+00, -2.39534068e+00],
       [ 9.86165311e-01,  1.14156669e+00,  9.72522021e-01,
         1.12577347e+00,  1.30317451e+00,  9.59067481e-01,
         1.11019875e+00,  1.28514550e+00,  1.48766062e+00],
       [ 1.58696606e-01,  6.05328256e-02,  2.51846129e-02,
         9.60635399e-03,  3.66422297e-03,  3.99671259e-03,
         1.52449578e-03,  5.81499750e-04,  2.21805770e-04],
       [ 7.57979405e-01,  4.14198529e-01,  5.74532779e-01,
         3.13953954e-01,  1.71560421e-01,  4.35484014e-01,
         2.37970632e-01,  1.30039266e-01,  7.10600740e-02],
       [-1.21576623e+00, -4.11145255e-01,  1.47808753e+00,
         4.99856517e-01,  1.69040421e-01, -1.79700890e+00,
        -6.07708673e-01, -2.05513635e-01, -6.95001668e-02],
       [-2.25800697e+00,  8.88552861e-01,  5.09859546e+00,
        -2.00635855e+00,  7.89526187e-01, -1.15126641e+01,
         4.53037158e+00, -1.78275563e+00,  7.01535752e-01],
       [ 1.45625531e+00,  3.01422940e-01,  2.12067952e+00,
         4.38948757e-01,  9.08557890e-02,  3.08825080e+00,
         6.39221456e-01,  1.32309225e-01,  2.73860191e-02],
       [ 3.61399765e-02,  1.42603393e+00,  1.30609790e-03,
         5.15368327e-02,  2.03357277e+00,  4.72023475e-05,
         1.86253992e-03,  7.34932721e-02,  2.89994376e+00],
       [-5.57048051e-02,  4.61284738e-01,  3.10302531e-03,
        -2.56957764e-02,  2.12783610e-01, -1.72853420e-04,
         1.43137822e-03, -1.18530695e-02,  9.81538316e-02],
       [ 6.49144854e-01,  1.37913599e+00,  4.21389041e-01,
         8.95259034e-01,  1.90201609e+00,  2.73542528e-01,
         5.81152794e-01,  1.23468396e+00,  2.62313885e+00],
       [-1.13415881e+00,  1.67968600e+00,  1.28631621e+00,
        -1.90503068e+00,  2.82134506e+00, -1.45888686e+00,
         2.16060733e+00, -3.19985336e+00,  4.73897380e+00],
       [ 5.81436398e-01, -6.20798817e-01,  3.38068285e-01,
        -3.60955028e-01,  3.85391172e-01,  1.96565206e-01,
        -2.09872391e-01,  2.24080455e-01, -2.39250384e-01],
       [-1.17277168e+00,  2.16104750e-01,  1.37539342e+00,
        -2.53441531e-01,  4.67012628e-02, -1.61302245e+00,
         2.97229050e-01, -5.47699185e-02,  1.00923647e-02],
       [ 1.13442051e+00, -2.16027782e+00,  1.28690989e+00,
        -2.45066346e+00,  4.66680027e+00,  1.45989697e+00,
        -2.78008289e+00,  5.29411393e+00, -1.00815851e+01],
       [-1.07500430e-01,  1.69368226e+00,  1.15563424e-02,
        -1.82071571e-01,  2.86855960e+00, -1.24231178e-03,
         1.95727721e-02, -3.08371390e-01,  4.85842851e+00],
       [ 1.42776185e+00, -1.39734389e+00,  2.03850391e+00,
        -1.99507430e+00,  1.95256994e+00,  2.91049812e+00,
        -2.84849098e+00,  2.78780487e+00, -2.72841167e+00],
       [ 1.24039432e+00, -7.77642106e-01,  1.53857806e+00,
        -9.64582850e-01,  6.04727245e-01,  1.90844349e+00,
        -1.19646309e+00,  7.50100238e-01, -4.70261368e-01],
       [-4.53873683e-01,  6.66054356e-01,  2.06001320e-01,
        -3.02304544e-01,  4.43628405e-01, -9.34985781e-02,
         1.37208077e-01, -2.01351258e-01,  2.95480631e-01],
       [ 1.69424498e+00, -1.30027911e+00,  2.87046604e+00,
        -2.20299135e+00,  1.69072577e+00,  4.86327267e+00,
        -3.73240704e+00,  2.86450364e+00, -2.19841541e+00],
       [ 2.67259699e-01,  1.18981651e+00,  7.14277466e-02,
         3.17990003e-01,  1.41566334e+00,  1.90897581e-02,
         8.49859124e-02,  3.78349757e-01,  1.68437961e+00],
       [ 9.96512931e-01, -4.15846846e-01,  9.93038022e-01,
        -4.14396759e-01,  1.72928599e-01,  9.89575230e-01,
        -4.12951729e-01,  1.72325585e-01, -7.19118127e-02],
       [-4.68382073e-01, -3.90908622e-01,  2.19381766e-01,
         1.83094591e-01,  1.52809551e-01, -1.02754486e-01,
        -8.57582239e-02, -7.15732543e-02, -5.97345711e-02],
       [ 3.51674085e-01,  2.55835181e-01,  1.23674662e-01,
         8.99706032e-02,  6.54516400e-02,  4.34931735e-02,
         3.16403295e-02,  2.30176456e-02,  1.67448322e-02],
       [ 1.72939819e+00,  6.66655232e-01,  2.99081810e+00,
         1.15291235e+00,  4.44429198e-01,  5.17231540e+00,
         1.99384453e+00,  7.68595050e-01,  2.96281050e-01],
       [-8.94666496e-01, -3.98243411e-01,  8.00428140e-01,
         3.56295037e-01,  1.58597814e-01, -7.16116240e-01,
        -3.18765232e-01, -1.41892151e-01, -6.31605344e-02],
       [ 3.60790492e+00, -2.50227902e-01,  1.30169779e+01,
        -9.02798479e-01,  6.26140029e-02,  4.69640188e+01,
        -3.25721108e+00,  2.25905369e-01, -1.56677706e-02],
       [-6.23089847e-01, -5.85274469e-01,  3.88240958e-01,
         3.64678579e-01,  3.42546204e-01, -2.41908999e-01,
        -2.27227520e-01, -2.13437062e-01, -2.00483547e-01],
       [-1.42506875e+00,  4.73903991e-01,  2.03082094e+00,
        -6.75345767e-01,  2.24584993e-01, -2.89405945e+00,
         9.62414147e-01, -3.20049054e-01,  1.06431724e-01],
       [-9.08327526e-01, -5.43634659e-02,  8.25058894e-01,
         4.93798325e-02,  2.95538643e-03, -7.49423703e-01,
        -4.48530610e-02, -2.68445884e-03, -1.60665049e-04],
       [ 1.14192505e+00, -1.51675945e+00,  1.30399281e+00,
        -1.73202561e+00,  2.30055923e+00,  1.48906206e+00,
        -1.97784342e+00,  2.62706621e+00, -3.48939495e+00],
       [-2.24588869e-01, -7.43858241e-01,  5.04401599e-02,
         1.67062281e-01,  5.53325083e-01, -1.13282985e-02,
        -3.75203286e-02, -1.24270654e-01, -4.11595423e-01],
       [-5.83521680e-01,  1.24080089e+00,  3.40497551e-01,
        -7.24034218e-01,  1.53958684e+00, -1.98687703e-01,
         4.22489663e-01, -8.98382300e-01,  1.91032072e+00],
       [-6.22795637e-01, -5.71973292e-01,  3.87874406e-01,
         3.56222471e-01,  3.27153446e-01, -2.41566488e-01,
        -2.21853801e-01, -2.03749739e-01, -1.87123033e-01],
       [ 5.48530599e-01,  8.43454281e-01,  3.00885818e-01,
         4.62660482e-01,  7.11415125e-01,  1.65045078e-01,
         2.53783432e-01,  3.90232965e-01,  6.00046133e-01],
       [ 1.02368000e+00, -1.22751654e+00,  1.04792074e+00,
        -1.25658413e+00,  1.50679685e+00,  1.07273551e+00,
        -1.28634004e+00,  1.54247780e+00, -1.84961805e+00],
       [ 4.23469085e-01,  5.94721406e-01,  1.79326066e-01,
         2.51846130e-01,  3.53693551e-01,  7.59390450e-02,
         1.06649050e-01,  1.49778284e-01,  2.10349126e-01],
       [-1.71877470e+00,  7.84463750e-01,  2.95418647e+00,
        -1.34831645e+00,  6.15383375e-01, -5.07758095e+00,
         2.31745219e+00, -1.05770538e+00,  4.82745950e-01],
       [-9.49125843e-01, -8.19676051e-01,  9.00839865e-01,
         7.77975722e-01,  6.71868828e-01, -8.55010396e-01,
        -7.38396863e-01, -6.37688068e-01, -5.50714788e-01],
       [ 9.19986506e-01,  1.10585020e+00,  8.46375171e-01,
         1.01736726e+00,  1.22290467e+00,  7.78653737e-01,
         9.35964153e-01,  1.12505579e+00,  1.35234937e+00],
       [-8.54324954e-01, -1.59329846e+00,  7.29871127e-01,
         1.36119463e+00,  2.53859998e+00, -6.23547116e-01,
        -1.16290254e+00, -2.16878931e+00, -4.04474743e+00],
       [ 3.25209143e-01, -6.93162776e-01,  1.05760986e-01,
        -2.25422872e-01,  4.80474634e-01,  3.43944397e-02,
        -7.33095790e-02,  1.56254744e-01, -3.33047131e-01],
       [ 9.08270789e-01, -1.07485660e+00,  8.24955826e-01,
        -9.76260848e-01,  1.15531670e+00,  7.49283280e-01,
        -8.86709211e-01,  1.04934041e+00, -1.24179978e+00],
       [-9.82912855e-01,  1.03944025e+00,  9.66117681e-01,
        -1.02167919e+00,  1.08043604e+00, -9.49609488e-01,
         1.00422161e+00, -1.06197447e+00,  1.12304871e+00],
       [-6.68326754e-01,  4.59363833e-01,  4.46660651e-01,
        -3.07005140e-01,  2.11015131e-01, -2.98515263e-01,
         2.05179749e-01, -1.41027058e-01,  9.69327194e-02],
       [-6.82105250e-01, -1.05153343e-01,  4.65267572e-01,
         7.17256472e-02,  1.10572255e-02, -3.17361454e-01,
        -4.89244406e-02, -7.54219158e-03, -1.16270423e-03],
       [-1.84873624e+00, -3.31291959e+00,  3.41782568e+00,
         6.12471451e+00,  1.09754362e+01, -6.31865819e+00,
        -1.13229817e+01, -2.02906867e+01, -3.63607378e+01],
       [-1.49817575e+00, -4.21268635e-01,  2.24453058e+00,
         6.31134453e-01,  1.77467263e-01, -3.36270129e+00,
        -9.45550333e-01, -2.65877149e-01, -7.47613914e-02],
       [ 8.41571229e-02, -2.55869710e-01,  7.08242134e-03,
        -2.15332586e-02,  6.54693083e-02,  5.96036203e-04,
        -1.81217709e-03,  5.50970863e-03, -1.67516129e-02],
       [-3.29899029e-01,  1.07513008e+00,  1.08833369e-01,
        -3.54684369e-01,  1.15590468e+00, -3.59040229e-02,
         1.17010029e-01, -3.81331832e-01,  1.24274789e+00],
       [-4.91067454e-01,  2.57325431e-01,  2.41147245e-01,
        -1.26364144e-01,  6.62163775e-02, -1.18419564e-01,
         6.20533187e-02, -3.25167079e-02,  1.70391579e-02],
       [-1.64937539e+00, -1.02645454e-02,  2.72043917e+00,
         1.69300886e-02,  1.05360892e-04, -4.48702542e+00,
        -2.79240714e-02, -1.73779663e-04, -1.08148166e-06],
       [-1.55233565e+00,  1.30098205e-01,  2.40974597e+00,
        -2.01956082e-01,  1.69255430e-02, -3.74073457e+00,
         3.13503626e-01, -2.62741238e-02,  2.20198277e-03],
       [-2.10257396e+00, -2.74921380e-01,  4.42081725e+00,
         5.78042534e-01,  7.55817652e-02, -9.29509522e+00,
        -1.21537718e+00, -1.58916251e-01, -2.07790432e-02],
       [ 4.37249217e-01,  1.76269490e+00,  1.91186877e-01,
         7.70736963e-01,  3.10709330e+00,  8.35963124e-02,
         3.37004133e-01,  1.35857411e+00,  5.47685750e+00],
       [ 2.01218334e+00,  7.19501194e-01,  4.04888181e+00,
         1.44776832e+00,  5.17681968e-01,  8.14709254e+00,
         2.91317530e+00,  1.04167103e+00,  3.72472794e-01],
       [ 1.34258423e+00,  8.69626381e-03,  1.80253242e+00,
         1.16754667e-02,  7.56250042e-05,  2.42005160e+00,
         1.56752974e-02,  1.01532938e-04,  6.57654987e-07],
       [ 1.31585947e+00, -3.74591532e-01,  1.73148614e+00,
        -4.92909813e-01,  1.40318816e-01,  2.27839242e+00,
        -6.48600044e-01,  1.84639842e-01, -5.25622401e-02],
       [-5.28887271e-01,  2.25008217e-01,  2.79721746e-01,
        -1.19003982e-01,  5.06286979e-02, -1.47941271e-01,
         6.29396914e-02, -2.67768739e-02,  1.13918730e-02],
       [ 1.94175988e-01,  6.68414008e-01,  3.77043142e-02,
         1.29789950e-01,  4.46777286e-01,  7.32127246e-03,
         2.52020918e-02,  8.67534208e-02,  2.98632196e-01],
       [-2.29412295e+00,  2.92730084e-01,  5.26300013e+00,
        -6.71558805e-01,  8.56909020e-02, -1.20739694e+01,
         1.54063847e+00, -1.96585465e-01,  2.50843049e-02],
       [-7.73996961e-01,  4.54938241e-01,  5.99071295e-01,
        -3.52120816e-01,  2.06968803e-01, -4.63679362e-01,
         2.72540442e-01, -1.60193225e-01,  9.41580234e-02],
       [-2.74810091e+00,  1.68131525e+00,  7.55205859e+00,
        -4.62042396e+00,  2.82682097e+00, -2.07538191e+01,
         1.26973913e+01, -7.76838926e+00,  4.75277720e+00],
       [ 1.42934465e+00,  8.35308694e-02,  2.04302612e+00,
         1.19394401e-01,  6.97740614e-03,  2.92018846e+00,
         1.70655748e-01,  9.97311813e-03,  5.82828801e-04],
       [ 5.73242338e-01, -1.32753296e+00,  3.28606779e-01,
        -7.60998100e-01,  1.76234377e+00,  1.88371318e-01,
        -4.36236331e-01,  1.01025006e+00, -2.33956945e+00],
       [-1.34810694e+00,  1.21320911e+00,  1.81739231e+00,
        -1.63553562e+00,  1.47187635e+00, -2.45003918e+00,
         2.20487691e+00, -1.98424672e+00,  1.78569381e+00],
       [-9.51954867e-01,  7.95959738e-01,  9.06218069e-01,
        -7.57717747e-01,  6.33551905e-01, -8.62678701e-01,
         7.21313097e-01, -6.03112820e-01,  5.04281809e-01],
       [ 1.29480025e+00,  1.05574888e+00,  1.67650769e+00,
         1.36698391e+00,  1.11460569e+00,  2.17074257e+00,
         1.76997110e+00,  1.44319172e+00,  1.17674370e+00],
       [ 1.32695326e+00, -1.47387716e+00,  1.76080495e+00,
        -1.95576609e+00,  2.17231387e+00,  2.33650586e+00,
        -2.59521019e+00,  2.88255897e+00, -3.20172379e+00],
       [ 2.11970790e+00, -8.96337870e-02,  4.49316157e+00,
        -1.89997446e-01,  8.03421576e-03,  9.52419006e+00,
        -4.02739087e-01,  1.70301906e-02, -7.20137184e-04],
       [-1.33885625e+00,  5.94917981e-01,  1.79253605e+00,
        -7.96509656e-01,  3.53927404e-01, -2.39994809e+00,
         1.06641193e+00, -4.73857916e-01,  2.10557777e-01],
       [-1.58048111e+00, -8.59834759e-01,  2.49792053e+00,
         1.35895259e+00,  7.39315813e-01, -3.94791620e+00,
        -2.14779889e+00, -1.16847467e+00, -6.35689434e-01],
       [-2.44614468e+00, -1.08021042e-01,  5.98362381e+00,
         2.64235098e-01,  1.16685456e-02, -1.46368095e+01,
        -6.46357281e-01, -2.85429508e-02, -1.26044846e-03],
       [-1.47547497e+00, -1.43197282e+00,  2.17702639e+00,
         2.11284005e+00,  2.05054616e+00, -3.21214795e+00,
        -3.11744262e+00, -3.02552953e+00, -2.93632636e+00],
       [-7.71374300e-01,  2.41883918e-02,  5.95018311e-01,
        -1.86583038e-02,  5.85078299e-04, -4.58981833e-01,
         1.43925360e-02, -4.51314364e-04,  1.41521032e-05],
       [ 2.05816194e+00, -1.13401491e+00,  4.23603057e+00,
        -2.33398632e+00,  1.28598981e+00,  8.71843688e+00,
        -4.80372181e+00,  2.64677529e+00, -1.45833162e+00],
       [ 1.50516689e+00, -1.29179972e+00,  2.26552737e+00,
        -1.94437416e+00,  1.66874651e+00,  3.40999679e+00,
        -2.92660761e+00,  2.51174199e+00, -2.15568626e+00],
       [-2.14860528e+00,  1.05086160e+00,  4.61650467e+00,
        -2.25788679e+00,  1.10431010e+00, -9.91904632e+00,
         4.85130748e+00, -2.37272652e+00,  1.16047708e+00],
       [ 8.93764040e-01, -4.23588082e-01,  7.98814158e-01,
        -3.78587795e-01,  1.79426863e-01,  7.13951369e-01,
        -3.38368157e-01,  1.60365278e-01, -7.60030806e-02],
       [-1.29931568e-01, -7.97168929e-01,  1.68822125e-02,
         1.03577409e-01,  6.35478302e-01, -2.19353234e-03,
        -1.34579752e-02, -8.25686924e-02, -5.06583558e-01],
       [ 1.42690239e+00,  1.24463899e+00,  2.03605044e+00,
         1.77597836e+00,  1.54912622e+00,  2.90524525e+00,
         2.53414777e+00,  2.21045191e+00,  1.92810289e+00],
       [-5.82968028e-01,  1.63075002e+00,  3.39851722e-01,
        -9.50675121e-01,  2.65934561e+00, -1.98122688e-01,
         5.54213200e-01, -1.55031347e+00,  4.33672790e+00],
       [-6.19719538e-01,  1.63084044e+00,  3.84052306e-01,
        -1.01066368e+00,  2.65964053e+00, -2.38004718e-01,
         6.26328031e-01, -1.64823120e+00,  4.33744933e+00],
       [ 1.93892868e+00,  6.99625802e-02,  3.75944443e+00,
         1.35652453e-01,  4.89476263e-03,  7.28929463e+00,
         2.63020432e-01,  9.49059564e-03,  3.42450223e-04]])

In [54]:
new_c = poly.get_feature_names(x.columns)
new_c

/Users/jung_yujin/miniconda3/envs/dssa/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['X1', 'X2', 'X1^2', 'X1 X2', 'X2^2', 'X1^3', 'X1^2 X2', 'X1 X2^2', 'X2^3']

In [56]:
pd.DataFrame(new_output, columns = new_c)

,X1,X2,X1^2,X1 X2,X2^2,X1^3,X1^2 X2,X1 X2^2,X2^3
0,-2.056844,-0.752741,4.230608,1.548270,0.566618,-8.701702,-3.184551,-1.165446,-0.426517
1,1.760238,1.558517,3.098437,2.743361,2.428977,5.453985,4.828968,4.275576,3.785603
2,-0.447763,-1.554927,0.200492,0.696238,2.417797,-0.089773,-0.311750,-1.082600,-3.759497
3,1.008459,0.529517,1.016990,0.533996,0.280388,1.025592,0.538513,0.282760,0.148470
4,0.636547,0.409058,0.405191,0.260384,0.167328,0.257923,0.165747,0.106512,0.068447
...,...,...,...,...,...,...,...,...,...
95,-0.129932,-0.797169,0.016882,0.103577,0.635478,-0.002194,-0.013458,-0.082569,-0.506584
96,1.426902,1.244639,2.036050,1.775978,1.549126,2.905245,2.534148,2.210452,1.928103
97,-0.582968,1.630750,0.339852,-0.950675,2.659346,-0.198123,0.554213,-1.550313,4.336728
98,-0.619720,1.630840,0.384052,-1.010664,2.659641,-0.238005,0.626328,-1.648231,4.337449
99,1.938929,0.069963,3.759444,0.135652,0.004895,7.289295,0.263020,0.009491,0.000342